import csv
import re
import logging
import pickle
import json
import argparse
import gensim
from gensim.corpora.dictionary import Dictionary
from gensim.models.ldamodel import LdaModel
import gensim.parsing.preprocessing as gpp

logging.basicConfig(level=logging.INFO)

parser = argparse.ArgumentParser()
parser.add_argument(
    "--model",
    dest="model",
    required=True,
    help="Model file generated by training script.")

parser.add_argument(
    "--data",
    dest="data",
    required=False,
    help="Data file model will be applied to."
)

parser.add_argument(
    "--per_word_counts_json",
    dest="counts",
    required=False,
    help="Counts output file."
)

args = parser.parse_args()

csv.field_size_limit(1000000000)

with open(args.model, "rb") as ifd:
    model = pickle.loads(ifd.read())

num_topics = model.num_topics
output = model.show_topics(num_topics = num_topics, num_words = 25, formatted = False)
for x in output:
    print("this is {}".format(x[0]))
    print(x)
